#!/bin/sh
# /usr/lib/emacsen-common/packages/remove/foo
# [ Sample only -- this script hasn't been tested, so be careful. ]
set -e

flavor="$1"
elc_dir="/usr/share/$flavor/site-lisp/foo"

echo "remove/foo: Handling removal of emacsen flavor $flavor"

(cd "$elc_dir" && rm -f *.elc *.el install.log install.log.gz)

if test -e "$elc_dir"
then
    rmdir --ignore-fail-on-non-empty "$elc_dir"
fi

exit 0
