#!/bin/sh
set -e
# Automatically added by dh_installinit/12.9ubuntu1
if [ "$1" = "purge" ] ; then
	update-rc.d x11-common remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/12.9ubuntu1
dpkg-maintscript-helper rm_conffile /etc/X11/Xsession.d/00upstart 1:7.7\+19ubuntu5\~ upstart -- "$@"
dpkg-maintscript-helper rm_conffile /etc/X11/Xsession.d/99upstart 1:7.7\+19ubuntu5\~ upstart -- "$@"
# End automatically added section
